// Auto-generated BPC data with quantity aggregation
// Generated by: update_bpc_data_js.py
// BPCs are grouped by type_id, ME, TE, and runs
const BPC_DATA = [
  {
    "typeId": 28297,
    "name": "'Augmented' Valkyrie Blueprint",
    "me": 0,
    "te": 0,
    "runs": 5,
    "quantity": 1,
    "category": "Drones",
    "subcategory": "Drones"
  },
  {
    "typeId": 28263,
    "name": "'Integrated' Acolyte Blueprint",
    "me": 0,
    "te": 0,
    "runs": 60,
    "quantity": 1,
    "category": "Drones",
    "subcategory": "Drones"
  },
  {
    "typeId": 28283,
    "name": "'Integrated' Infiltrator Blueprint",
    "me": 0,
    "te": 0,
    "runs": 1,
    "quantity": 1,
    "category": "Drones",
    "subcategory": "Drones"
  },
  {
    "typeId": 28283,
    "name": "'Integrated' Infiltrator Blueprint",
    "me": 0,
    "te": 0,
    "runs": 60,
    "quantity": 2,
    "category": "Drones",
    "subcategory": "Drones"
  },
  {
    "typeId": 28291,
    "name": "'Integrated' Praetor Blueprint",
    "me": 0,
    "te": 0,
    "runs": 60,
    "quantity": 1,
    "category": "Drones",
    "subcategory": "Drones"
  },
  {
    "typeId": 28295,
    "name": "'Integrated' Valkyrie Blueprint",
    "me": 0,
    "te": 0,
    "runs": 60,
    "quantity": 1,
    "category": "Drones",
    "subcategory": "Drones"
  },
  {
    "typeId": 23814,
    "name": "'Palisade' Cap Recharger I Blueprint",
    "me": 0,
    "te": 0,
    "runs": 3,
    "quantity": 1,
    "category": "Ammunition",
    "subcategory": "Capacitor Modules"
  },
  {
    "typeId": 12059,
    "name": "10MN Afterburner II Blueprint",
    "me": 3,
    "te": 2,
    "runs": 13,
    "quantity": 1,
    "category": "Modules",
    "subcategory": "Propulsion Modules"
  },
  {
    "typeId": 11280,
    "name": "1600mm Steel Plates I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 60,
    "quantity": 12,
    "category": "Modules",
    "subcategory": "Armor Modules"
  },
  {
    "typeId": 12357,
    "name": "350mm Railgun II Blueprint",
    "me": 7,
    "te": 14,
    "runs": 1,
    "quantity": 1,
    "category": "Modules",
    "subcategory": "Weapon Modules"
  },
  {
    "typeId": 1073,
    "name": "5MN Microwarpdrive II Blueprint",
    "me": 3,
    "te": 2,
    "runs": 13,
    "quantity": 4,
    "category": "Modules",
    "subcategory": "Propulsion Modules"
  },
  {
    "typeId": 24693,
    "name": "Abaddon Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 24693,
    "name": "Abaddon Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 23920,
    "name": "Aeon Blueprint",
    "me": 5,
    "te": 10,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 32873,
    "name": "Algos Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Destroyer"
  },
  {
    "typeId": 996,
    "name": "Apocalypse Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 996,
    "name": "Apocalypse Blueprint",
    "me": 10,
    "te": 20,
    "runs": 9,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 996,
    "name": "Apocalypse Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 23758,
    "name": "Archon Blueprint",
    "me": 10,
    "te": 16,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 997,
    "name": "Armageddon Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 2,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 997,
    "name": "Armageddon Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 955,
    "name": "Atron Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Frigate"
  },
  {
    "typeId": 11986,
    "name": "Basilisk Blueprint",
    "me": 3,
    "te": 2,
    "runs": 4,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 34329,
    "name": "Bowhead Blueprint",
    "me": 6,
    "te": 8,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Freighter Blueprint"
  },
  {
    "typeId": 34329,
    "name": "Bowhead Blueprint",
    "me": 6,
    "te": 10,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Freighter Blueprint"
  },
  {
    "typeId": 945,
    "name": "Breacher Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 2,
    "category": "Ships",
    "subcategory": "Frigate"
  },
  {
    "typeId": 16230,
    "name": "Brutix Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battlecruiser"
  },
  {
    "typeId": 11193,
    "name": "Buzzard Blueprint",
    "me": 5,
    "te": 10,
    "runs": 1,
    "quantity": 6,
    "category": "Ships",
    "subcategory": "Frigate"
  },
  {
    "typeId": 3537,
    "name": "CONCORD Capital Remote Armor Repairer Blueprint",
    "me": 0,
    "te": 0,
    "runs": 2,
    "quantity": 1,
    "category": "Modules",
    "subcategory": "Armor Modules"
  },
  {
    "typeId": 3545,
    "name": "CONCORD Capital Remote Shield Booster Blueprint",
    "me": 0,
    "te": 0,
    "runs": 2,
    "quantity": 1,
    "category": "Modules",
    "subcategory": "Shield Modules"
  },
  {
    "typeId": 41603,
    "name": "CONCORD Capital Shield Extender Blueprint",
    "me": 0,
    "te": 0,
    "runs": 1,
    "quantity": 1,
    "category": "Modules",
    "subcategory": "Shield Modules"
  },
  {
    "typeId": 31363,
    "name": "Capital Ancillary Current Router I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 12,
    "quantity": 1,
    "category": "Rigs",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21018,
    "name": "Capital Armor Plates Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21018,
    "name": "Capital Armor Plates Blueprint",
    "me": 10,
    "te": 20,
    "runs": 13,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21018,
    "name": "Capital Armor Plates Blueprint",
    "me": 10,
    "te": 20,
    "runs": 16,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 20702,
    "name": "Capital Armor Repairer I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 1,
    "category": "Modules",
    "subcategory": "Armor Modules"
  },
  {
    "typeId": 41641,
    "name": "Capital Cap Battery II Blueprint",
    "me": 3,
    "te": 12,
    "runs": 6,
    "quantity": 1,
    "category": "Modules",
    "subcategory": "Capacitor Modules"
  },
  {
    "typeId": 21020,
    "name": "Capital Capacitor Battery Blueprint",
    "me": 10,
    "te": 20,
    "runs": 5,
    "quantity": 2,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21020,
    "name": "Capital Capacitor Battery Blueprint",
    "me": 10,
    "te": 20,
    "runs": 19,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21020,
    "name": "Capital Capacitor Battery Blueprint",
    "me": 10,
    "te": 20,
    "runs": 21,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 41646,
    "name": "Capital Capacitor Booster II Blueprint",
    "me": 5,
    "te": 10,
    "runs": 3,
    "quantity": 1,
    "category": "Modules",
    "subcategory": "Capacitor Modules"
  },
  {
    "typeId": 21028,
    "name": "Capital Cargo Bay Blueprint",
    "me": 10,
    "te": 16,
    "runs": 10,
    "quantity": 3,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21028,
    "name": "Capital Cargo Bay Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21028,
    "name": "Capital Cargo Bay Blueprint",
    "me": 10,
    "te": 20,
    "runs": 3,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21028,
    "name": "Capital Cargo Bay Blueprint",
    "me": 10,
    "te": 20,
    "runs": 5,
    "quantity": 11,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21028,
    "name": "Capital Cargo Bay Blueprint",
    "me": 10,
    "te": 20,
    "runs": 19,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21028,
    "name": "Capital Cargo Bay Blueprint",
    "me": 10,
    "te": 20,
    "runs": 37,
    "quantity": 2,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 24548,
    "name": "Capital Clone Vat Bay Blueprint",
    "me": 10,
    "te": 18,
    "runs": 21,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 24548,
    "name": "Capital Clone Vat Bay Blueprint",
    "me": 10,
    "te": 20,
    "runs": 3,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 24548,
    "name": "Capital Clone Vat Bay Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21036,
    "name": "Capital Computer System Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 2,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21036,
    "name": "Capital Computer System Blueprint",
    "me": 10,
    "te": 20,
    "runs": 5,
    "quantity": 3,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21036,
    "name": "Capital Computer System Blueprint",
    "me": 10,
    "te": 20,
    "runs": 9,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21036,
    "name": "Capital Computer System Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21038,
    "name": "Capital Construction Parts Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21038,
    "name": "Capital Construction Parts Blueprint",
    "me": 10,
    "te": 20,
    "runs": 4,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21038,
    "name": "Capital Construction Parts Blueprint",
    "me": 10,
    "te": 20,
    "runs": 5,
    "quantity": 9,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 24561,
    "name": "Capital Corporate Hangar Bay Blueprint",
    "me": 8,
    "te": 8,
    "runs": 8,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 24561,
    "name": "Capital Corporate Hangar Bay Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 24561,
    "name": "Capital Corporate Hangar Bay Blueprint",
    "me": 10,
    "te": 20,
    "runs": 5,
    "quantity": 2,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 24561,
    "name": "Capital Corporate Hangar Bay Blueprint",
    "me": 10,
    "te": 20,
    "runs": 18,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21030,
    "name": "Capital Drone Bay Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 6,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21030,
    "name": "Capital Drone Bay Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21030,
    "name": "Capital Drone Bay Blueprint",
    "me": 10,
    "te": 20,
    "runs": 4,
    "quantity": 4,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21030,
    "name": "Capital Drone Bay Blueprint",
    "me": 10,
    "te": 20,
    "runs": 5,
    "quantity": 5,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 31477,
    "name": "Capital Energy Discharge Elutriation II Blueprint",
    "me": 0,
    "te": 0,
    "runs": 2,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 21026,
    "name": "Capital Jump Drive Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21026,
    "name": "Capital Jump Drive Blueprint",
    "me": 10,
    "te": 20,
    "runs": 33,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21022,
    "name": "Capital Power Generator Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21022,
    "name": "Capital Power Generator Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21022,
    "name": "Capital Power Generator Blueprint",
    "me": 10,
    "te": 20,
    "runs": 5,
    "quantity": 2,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 33304,
    "name": "Capital Processor Overclocking Unit I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 11,
    "quantity": 1,
    "category": "Rigs",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 33306,
    "name": "Capital Processor Overclocking Unit II Blueprint",
    "me": 3,
    "te": 2,
    "runs": 1,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 21010,
    "name": "Capital Propulsion Engine Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21010,
    "name": "Capital Propulsion Engine Blueprint",
    "me": 10,
    "te": 20,
    "runs": 5,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21014,
    "name": "Capital Sensor Cluster Blueprint",
    "me": 10,
    "te": 20,
    "runs": 3,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21014,
    "name": "Capital Sensor Cluster Blueprint",
    "me": 10,
    "te": 20,
    "runs": 5,
    "quantity": 3,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21014,
    "name": "Capital Sensor Cluster Blueprint",
    "me": 10,
    "te": 20,
    "runs": 11,
    "quantity": 2,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21014,
    "name": "Capital Sensor Cluster Blueprint",
    "me": 10,
    "te": 20,
    "runs": 26,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 20704,
    "name": "Capital Shield Booster I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 1,
    "category": "Modules",
    "subcategory": "Shield Modules"
  },
  {
    "typeId": 41634,
    "name": "Capital Shield Booster II Blueprint",
    "me": 3,
    "te": 2,
    "runs": 5,
    "quantity": 1,
    "category": "Modules",
    "subcategory": "Shield Modules"
  },
  {
    "typeId": 21024,
    "name": "Capital Shield Emitter Blueprint",
    "me": 9,
    "te": 14,
    "runs": 6,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21024,
    "name": "Capital Shield Emitter Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21024,
    "name": "Capital Shield Emitter Blueprint",
    "me": 10,
    "te": 20,
    "runs": 27,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 41602,
    "name": "Capital Shield Extender II Blueprint",
    "me": 5,
    "te": 10,
    "runs": 1,
    "quantity": 1,
    "category": "Modules",
    "subcategory": "Shield Modules"
  },
  {
    "typeId": 24559,
    "name": "Capital Ship Maintenance Bay Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 3,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 24559,
    "name": "Capital Ship Maintenance Bay Blueprint",
    "me": 10,
    "te": 20,
    "runs": 5,
    "quantity": 5,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21040,
    "name": "Capital Siege Array Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21040,
    "name": "Capital Siege Array Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21040,
    "name": "Capital Siege Array Blueprint",
    "me": 10,
    "te": 20,
    "runs": 4,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21040,
    "name": "Capital Siege Array Blueprint",
    "me": 10,
    "te": 20,
    "runs": 5,
    "quantity": 4,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 21012,
    "name": "Capital Turret Hardpoint Blueprint",
    "me": 10,
    "te": 20,
    "runs": 13,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 687,
    "name": "Caracal Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 687,
    "name": "Caracal Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 3,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 687,
    "name": "Caracal Blueprint",
    "me": 10,
    "te": 20,
    "runs": 3,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 687,
    "name": "Caracal Blueprint",
    "me": 10,
    "te": 20,
    "runs": 8,
    "quantity": 2,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 687,
    "name": "Caracal Blueprint",
    "me": 10,
    "te": 20,
    "runs": 9,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 16241,
    "name": "Catalyst Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 3,
    "category": "Ships",
    "subcategory": "Destroyer"
  },
  {
    "typeId": 11994,
    "name": "Cerberus Blueprint",
    "me": 3,
    "te": 2,
    "runs": 4,
    "quantity": 2,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 11994,
    "name": "Cerberus Blueprint",
    "me": 5,
    "te": 10,
    "runs": 1,
    "quantity": 4,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 20186,
    "name": "Charon Blueprint",
    "me": 8,
    "te": 10,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Freighter Blueprint"
  },
  {
    "typeId": 20186,
    "name": "Charon Blueprint",
    "me": 10,
    "te": 18,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Freighter Blueprint"
  },
  {
    "typeId": 23916,
    "name": "Chimera Blueprint",
    "me": 10,
    "te": 16,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 684,
    "name": "Condor Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 2,
    "category": "Ships",
    "subcategory": "Frigate"
  },
  {
    "typeId": 684,
    "name": "Condor Blueprint",
    "me": 10,
    "te": 20,
    "runs": 30,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Frigate"
  },
  {
    "typeId": 12815,
    "name": "Conflagration M Blueprint",
    "me": 7,
    "te": 14,
    "runs": 10,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Frequency Crystals"
  },
  {
    "typeId": 32877,
    "name": "Corax Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 2,
    "category": "Ships",
    "subcategory": "Destroyer"
  },
  {
    "typeId": 16239,
    "name": "Cormorant Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 3,
    "category": "Ships",
    "subcategory": "Destroyer"
  },
  {
    "typeId": 17477,
    "name": "Covetor Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 22,
    "category": "Ships",
    "subcategory": "Mining Barge Blueprint"
  },
  {
    "typeId": 16232,
    "name": "Cyclone Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battlecruiser"
  },
  {
    "typeId": 22475,
    "name": "Damnation Blueprint",
    "me": 3,
    "te": 2,
    "runs": 4,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battlecruiser"
  },
  {
    "typeId": 999,
    "name": "Dominix Blueprint",
    "me": 10,
    "te": 20,
    "runs": 5,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 999,
    "name": "Dominix Blueprint",
    "me": 10,
    "te": 20,
    "runs": 6,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 999,
    "name": "Dominix Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 23058,
    "name": "Dragonfly I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 2,
    "category": "Drones",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 32875,
    "name": "Dragoon Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Destroyer"
  },
  {
    "typeId": 24699,
    "name": "Drake Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 3,
    "category": "Ships",
    "subcategory": "Battlecruiser"
  },
  {
    "typeId": 24699,
    "name": "Drake Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 3,
    "category": "Ships",
    "subcategory": "Battlecruiser"
  },
  {
    "typeId": 27948,
    "name": "Dread Guristas Torpedo Battery Blueprint",
    "me": 0,
    "te": 0,
    "runs": 3,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 23062,
    "name": "Einherji I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 9,
    "category": "Drones",
    "subcategory": "Fighters"
  },
  {
    "typeId": 41384,
    "name": "Einherji II Blueprint",
    "me": 5,
    "te": 10,
    "runs": 3,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 39583,
    "name": "Endurance Blueprint",
    "me": 3,
    "te": 2,
    "runs": 4,
    "quantity": 2,
    "category": "Ships",
    "subcategory": "Frigate"
  },
  {
    "typeId": 12045,
    "name": "Enyo Blueprint",
    "me": 5,
    "te": 10,
    "runs": 1,
    "quantity": 15,
    "category": "Ships",
    "subcategory": "Frigate"
  },
  {
    "typeId": 41376,
    "name": "Equite I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 5,
    "quantity": 1,
    "category": "Drones",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 16228,
    "name": "Ferox Blueprint",
    "me": 10,
    "te": 20,
    "runs": 9,
    "quantity": 2,
    "category": "Ships",
    "subcategory": "Battlecruiser"
  },
  {
    "typeId": 16228,
    "name": "Ferox Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battlecruiser"
  },
  {
    "typeId": 24284,
    "name": "Fighter Support Unit I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 2,
    "category": "Modules",
    "subcategory": "Drones"
  },
  {
    "typeId": 24284,
    "name": "Fighter Support Unit I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 4,
    "quantity": 1,
    "category": "Modules",
    "subcategory": "Drones"
  },
  {
    "typeId": 41416,
    "name": "Fighter Support Unit II Blueprint",
    "me": 5,
    "te": 10,
    "runs": 2,
    "quantity": 1,
    "category": "Drones",
    "subcategory": "Drones"
  },
  {
    "typeId": 23060,
    "name": "Firbolg I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 2,
    "category": "Drones",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 17331,
    "name": "Fusion Reactor Unit Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1970,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Ship Components"
  },
  {
    "typeId": 17340,
    "name": "Gravimetric Sensor Cluster Blueprint",
    "me": 10,
    "te": 20,
    "runs": 3519,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Ship Components"
  },
  {
    "typeId": 2184,
    "name": "Hammerhead I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1500,
    "quantity": 6,
    "category": "Drones",
    "subcategory": "Drones"
  },
  {
    "typeId": 24697,
    "name": "Harbinger Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battlecruiser"
  },
  {
    "typeId": 48472,
    "name": "Heavy Scoped Entropic Disintegrator Blueprint",
    "me": 0,
    "te": 0,
    "runs": 1,
    "quantity": 1,
    "category": "Modules",
    "subcategory": "Weapon Modules"
  },
  {
    "typeId": 2455,
    "name": "Hobgoblin I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1500,
    "quantity": 6,
    "category": "Drones",
    "subcategory": "Drones"
  },
  {
    "typeId": 2457,
    "name": "Hobgoblin II Blueprint",
    "me": 2,
    "te": 4,
    "runs": 10,
    "quantity": 1,
    "category": "Drones",
    "subcategory": "Drones"
  },
  {
    "typeId": 2465,
    "name": "Hornet I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1500,
    "quantity": 5,
    "category": "Drones",
    "subcategory": "Drones"
  },
  {
    "typeId": 22545,
    "name": "Hulk Blueprint",
    "me": 5,
    "te": 10,
    "runs": 1,
    "quantity": 3,
    "category": "Ships",
    "subcategory": "Mining Barge Blueprint"
  },
  {
    "typeId": 24703,
    "name": "Hurricane Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battlecruiser"
  },
  {
    "typeId": 4316,
    "name": "Hydrogen Fuel Block Blueprint",
    "me": 10,
    "te": 20,
    "runs": 200,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Fuel Blocks"
  },
  {
    "typeId": 24691,
    "name": "Hyperion Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 43912,
    "name": "Ice Harvesting Drone II Blueprint",
    "me": 3,
    "te": 12,
    "runs": 12,
    "quantity": 5,
    "category": "Drones",
    "subcategory": "Drones"
  },
  {
    "typeId": 941,
    "name": "Incursus Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 2,
    "category": "Ships",
    "subcategory": "Frigate"
  },
  {
    "typeId": 12006,
    "name": "Ishtar Blueprint",
    "me": 4,
    "te": 14,
    "runs": 2,
    "quantity": 2,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 949,
    "name": "Kestrel Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Frigate"
  },
  {
    "typeId": 26343,
    "name": "Large Emission Scope Sharpener II Blueprint",
    "me": 0,
    "te": 0,
    "runs": 2,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 26387,
    "name": "Large Energy Ambit Extension II Blueprint",
    "me": 0,
    "te": 0,
    "runs": 2,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 26349,
    "name": "Large Liquid Cooled Electronics II Blueprint",
    "me": 0,
    "te": 0,
    "runs": 2,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 26419,
    "name": "Large Rocket Fuel Cache Partition II Blueprint",
    "me": 0,
    "te": 0,
    "runs": 2,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 26345,
    "name": "Large Signal Disruption Amplifier II Blueprint",
    "me": 0,
    "te": 0,
    "runs": 2,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 41535,
    "name": "Ligature Integrated Analyzer Blueprint",
    "me": 0,
    "te": 0,
    "runs": 3,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 24695,
    "name": "Maelstrom Blueprint",
    "me": 10,
    "te": 20,
    "runs": 9,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 969,
    "name": "Maller Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 3,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 969,
    "name": "Maller Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 2,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 31361,
    "name": "Medium Ancillary Current Router I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 40,
    "quantity": 1,
    "category": "Rigs",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 31379,
    "name": "Medium Capacitor Control Circuit II Blueprint",
    "me": 0,
    "te": 0,
    "runs": 2,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 31415,
    "name": "Medium Semiconductor Memory Cell II Blueprint",
    "me": 0,
    "te": 0,
    "runs": 2,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 31042,
    "name": "Medium Thermal Armor Reinforcer II Blueprint",
    "me": 0,
    "te": 0,
    "runs": 2,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 995,
    "name": "Megathron Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 2,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 995,
    "name": "Megathron Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 950,
    "name": "Merlin Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 2,
    "category": "Ships",
    "subcategory": "Frigate"
  },
  {
    "typeId": 968,
    "name": "Moa Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 8,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 968,
    "name": "Moa Blueprint",
    "me": 10,
    "te": 20,
    "runs": 8,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 968,
    "name": "Moa Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 2,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 90039,
    "name": "Mobile Phase Anchor Blueprint",
    "me": 2,
    "te": 2,
    "runs": 1,
    "quantity": 1,
    "category": "Structures",
    "subcategory": "Mobile Phase Anchor Blueprint"
  },
  {
    "typeId": 33519,
    "name": "Mobile Tractor Unit Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 2,
    "category": "Structures",
    "subcategory": "Deployable Structures"
  },
  {
    "typeId": 17913,
    "name": "Modulated Strip Miner II Blueprint",
    "me": 7,
    "te": 14,
    "runs": 10,
    "quantity": 3,
    "category": "Other",
    "subcategory": "Strip Miner Blueprint"
  },
  {
    "typeId": 24701,
    "name": "Myrmidon Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battlecruiser"
  },
  {
    "typeId": 4307,
    "name": "Naga Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battlecruiser"
  },
  {
    "typeId": 3187,
    "name": "Neutron Blaster Cannon II Blueprint",
    "me": 7,
    "te": 14,
    "runs": 10,
    "quantity": 1,
    "category": "Modules",
    "subcategory": "Weapon Modules"
  },
  {
    "typeId": 24484,
    "name": "Nidhoggur Blueprint",
    "me": 7,
    "te": 10,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 24484,
    "name": "Nidhoggur Blueprint",
    "me": 9,
    "te": 14,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 22471,
    "name": "Nighthawk Blueprint",
    "me": 3,
    "te": 2,
    "runs": 4,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battlecruiser"
  },
  {
    "typeId": 2445,
    "name": "Ogre I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1500,
    "quantity": 6,
    "category": "Drones",
    "subcategory": "Drones"
  },
  {
    "typeId": 2007,
    "name": "Omen Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 5,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 4305,
    "name": "Oracle Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battlecruiser"
  },
  {
    "typeId": 28607,
    "name": "Orca Blueprint",
    "me": 7,
    "te": 14,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Industrial Command Ship"
  },
  {
    "typeId": 28607,
    "name": "Orca Blueprint",
    "me": 8,
    "te": 16,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Industrial Command Ship"
  },
  {
    "typeId": 28660,
    "name": "Paladin Blueprint",
    "me": 5,
    "te": 10,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 19727,
    "name": "Phoenix Blueprint",
    "me": 10,
    "te": 18,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 17357,
    "name": "Photon Microprocessor Blueprint",
    "me": 10,
    "te": 20,
    "runs": 6253,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Ship Components"
  },
  {
    "typeId": 17324,
    "name": "Plasma Thruster Blueprint",
    "me": 10,
    "te": 20,
    "runs": 3944,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Ship Components"
  },
  {
    "typeId": 17481,
    "name": "Procurer Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Mining Barge Blueprint"
  },
  {
    "typeId": 17481,
    "name": "Procurer Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 14,
    "category": "Ships",
    "subcategory": "Mining Barge Blueprint"
  },
  {
    "typeId": 16234,
    "name": "Prophecy Blueprint",
    "me": 10,
    "te": 20,
    "runs": 5,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battlecruiser"
  },
  {
    "typeId": 16234,
    "name": "Prophecy Blueprint",
    "me": 10,
    "te": 20,
    "runs": 9,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battlecruiser"
  },
  {
    "typeId": 944,
    "name": "Punisher Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Frigate"
  },
  {
    "typeId": 688,
    "name": "Raven Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 6,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 688,
    "name": "Raven Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 17479,
    "name": "Retriever Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 3,
    "category": "Ships",
    "subcategory": "Mining Barge Blueprint"
  },
  {
    "typeId": 17479,
    "name": "Retriever Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 13,
    "category": "Ships",
    "subcategory": "Mining Barge Blueprint"
  },
  {
    "typeId": 24689,
    "name": "Rokh Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 974,
    "name": "Rupture Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 3,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 32982,
    "name": "Salvage Drone I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 100,
    "quantity": 1,
    "category": "Drones",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 27812,
    "name": "Sansha Small Beam Laser Battery Blueprint",
    "me": 0,
    "te": 0,
    "runs": 3,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 12821,
    "name": "Scorch L Blueprint",
    "me": 7,
    "te": 14,
    "runs": 10,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Frequency Crystals"
  },
  {
    "typeId": 994,
    "name": "Scorpion Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 1220,
    "name": "Scourge Rocket Blueprint",
    "me": 10,
    "te": 20,
    "runs": 5,
    "quantity": 1,
    "category": "Ammunition",
    "subcategory": "Rockets"
  },
  {
    "typeId": 976,
    "name": "Scythe Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 9,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 27845,
    "name": "Serpentis Small Railgun Battery Blueprint",
    "me": 0,
    "te": 0,
    "runs": 3,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 19745,
    "name": "Sigil Blueprint",
    "me": 10,
    "te": 16,
    "runs": 5,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Hauler"
  },
  {
    "typeId": 60341,
    "name": "Simple Asteroid Mining Crystal Type A I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 97,
    "quantity": 1,
    "category": "Ammunition",
    "subcategory": "Mining Crystal"
  },
  {
    "typeId": 60341,
    "name": "Simple Asteroid Mining Crystal Type A I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 600,
    "quantity": 1,
    "category": "Ammunition",
    "subcategory": "Mining Crystal"
  },
  {
    "typeId": 60342,
    "name": "Simple Asteroid Mining Crystal Type A II Blueprint",
    "me": 2,
    "te": 4,
    "runs": 10,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Mining Crystal Blueprint"
  },
  {
    "typeId": 689,
    "name": "Slasher Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 3,
    "category": "Ships",
    "subcategory": "Frigate"
  },
  {
    "typeId": 33077,
    "name": "Small Ancillary Armor Repairer Blueprint",
    "me": 0,
    "te": 0,
    "runs": 50,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 31359,
    "name": "Small Ancillary Current Router I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 40,
    "quantity": 1,
    "category": "Rigs",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 32054,
    "name": "Small Drone Repair Augmentor II Blueprint",
    "me": 0,
    "te": 0,
    "runs": 2,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 31016,
    "name": "Small Explosive Armor Reinforcer II Blueprint",
    "me": 0,
    "te": 0,
    "runs": 2,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 31221,
    "name": "Small Gravity Capacitor Upgrade II Blueprint",
    "me": 0,
    "te": 0,
    "runs": 2,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 31557,
    "name": "Small Hybrid Discharge Elutriation II Blueprint",
    "me": 0,
    "te": 0,
    "runs": 2,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 31413,
    "name": "Small Semiconductor Memory Cell II Blueprint",
    "me": 0,
    "te": 0,
    "runs": 2,
    "quantity": 1,
    "category": "Other",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 692,
    "name": "Stabber Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 6,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 692,
    "name": "Stabber Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 4,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 45643,
    "name": "Standup L-Set Thukker Advanced Component Manufacturing Efficiency Blueprint",
    "me": 0,
    "te": 0,
    "runs": 1,
    "quantity": 1,
    "category": "Rigs",
    "subcategory": "Rigs"
  },
  {
    "typeId": 45545,
    "name": "Standup M-Set Thukker Basic Capital Component Manufacturing Material Efficiency Blueprint",
    "me": 0,
    "te": 0,
    "runs": 1,
    "quantity": 2,
    "category": "Rigs",
    "subcategory": "Rigs"
  },
  {
    "typeId": 17352,
    "name": "Sustained Shield Emitter Blueprint",
    "me": 10,
    "te": 20,
    "runs": 3708,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Ship Components"
  },
  {
    "typeId": 4309,
    "name": "Talos Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battlecruiser"
  },
  {
    "typeId": 32879,
    "name": "Talwar Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Destroyer"
  },
  {
    "typeId": 693,
    "name": "Tempest Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 693,
    "name": "Tempest Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 23056,
    "name": "Templar I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 2,
    "category": "Drones",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 17334,
    "name": "Tesseract Capacitor Unit Blueprint",
    "me": 10,
    "te": 20,
    "runs": 3636,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Ship Components"
  },
  {
    "typeId": 23912,
    "name": "Thanatos Blueprint",
    "me": 10,
    "te": 12,
    "runs": 1,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Capital Ship"
  },
  {
    "typeId": 972,
    "name": "Thorax Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 2,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 16243,
    "name": "Thrasher Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 2,
    "category": "Ships",
    "subcategory": "Destroyer"
  },
  {
    "typeId": 938,
    "name": "Tormentor Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 3,
    "category": "Ships",
    "subcategory": "Frigate"
  },
  {
    "typeId": 4311,
    "name": "Tornado Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 7,
    "category": "Ships",
    "subcategory": "Battlecruiser"
  },
  {
    "typeId": 17350,
    "name": "Tungsten Carbide Armor Plate Blueprint",
    "me": 10,
    "te": 20,
    "runs": 16361,
    "quantity": 1,
    "category": "Components",
    "subcategory": "Ship Components"
  },
  {
    "typeId": 998,
    "name": "Typhoon Blueprint",
    "me": 10,
    "te": 20,
    "runs": 1,
    "quantity": 3,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 998,
    "name": "Typhoon Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Battleship"
  },
  {
    "typeId": 32343,
    "name": "Tyrfing I Blueprint",
    "me": 10,
    "te": 20,
    "runs": 10,
    "quantity": 1,
    "category": "Drones",
    "subcategory": "Uncategorized"
  },
  {
    "typeId": 1135,
    "name": "Uranium Charge S Blueprint",
    "me": 10,
    "te": 20,
    "runs": 5,
    "quantity": 1,
    "category": "Ammunition",
    "subcategory": "Hybrid Charges"
  },
  {
    "typeId": 971,
    "name": "Vexor Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 2,
    "category": "Ships",
    "subcategory": "Cruiser"
  },
  {
    "typeId": 12792,
    "name": "Void L Blueprint",
    "me": 2,
    "te": 4,
    "runs": 10,
    "quantity": 1,
    "category": "Ammunition",
    "subcategory": "Hybrid Charges"
  },
  {
    "typeId": 2489,
    "name": "Warrior II Blueprint",
    "me": 2,
    "te": 4,
    "runs": 10,
    "quantity": 1,
    "category": "Drones",
    "subcategory": "Drones"
  },
  {
    "typeId": 41536,
    "name": "Zeugma Integrated Analyzer Blueprint",
    "me": 0,
    "te": 0,
    "runs": 3,
    "quantity": 4,
    "category": "Other",
    "subcategory": "Uncategorized"
  }
];