"""
Update bpc_data.js with BPC data (blueprint copies with quantity aggregation).
BPCs are grouped by type_id, ME, TE, and runs.
"""
import sys
import os
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, PROJECT_DIR)

from generate_corrected_html import categorize_blueprint, get_subcategory, get_market_group_path
import sqlite3
import json

DB_PATH = os.path.join(PROJECT_DIR, 'mydatabase.db')

def get_bpcs_with_metadata():
    """Get all BPCs with categorization and quantity aggregation."""
    print("Querying BPCs from database...")
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    query = """
        SELECT
            cb.type_id,
            cb.type_name,
            cb.material_efficiency as ME,
            cb.time_efficiency as TE,
            cb.runs,
            COUNT(*) as quantity,
            COALESCE(g.group_name, 'Unknown') as group_name,
            t.market_group_id
        FROM character_blueprints cb
        LEFT JOIN inv_types t ON cb.type_id = t.type_id
        LEFT JOIN inv_groups g ON t.group_id = g.group_id
        WHERE cb.runs > 0
        GROUP BY cb.type_id, cb.material_efficiency, cb.time_efficiency, cb.runs
        ORDER BY cb.type_name
    """

    cursor.execute(query)
    results = cursor.fetchall()

    bpcs = []
    for row in results:
        type_id, name, me, te, runs, quantity, group_name, market_group_id = row

        # Get market path for categorization
        market_path = get_market_group_path(cursor, market_group_id)

        # Categorize (uses override system + market group IDs)
        category = categorize_blueprint(group_name, name, market_path, type_id, market_group_id, cursor)
        subcategory = get_subcategory(group_name, name, market_path, type_id)

        bpcs.append({
            'typeId': type_id,
            'name': name,
            'me': me,
            'te': te,
            'runs': runs,
            'quantity': quantity,
            'category': category,
            'subcategory': subcategory
        })

    conn.close()
    return bpcs


print("=" * 70)
print("BPC DATA GENERATION")
print("=" * 70)
print()

bpcs = get_bpcs_with_metadata()

print(f"BPCs found (after grouping): {len(bpcs)}")
print()

if bpcs:
    # Show some statistics
    total_copies = sum(bpc['quantity'] for bpc in bpcs)
    print(f"Total individual BPC items: {total_copies}")
    print()

    # Show sample
    print("Sample BPCs:")
    for bpc in bpcs[:5]:
        print(f"  {bpc['name']} (ME{bpc['me']}/TE{bpc['te']}, {bpc['runs']} runs) x{bpc['quantity']}")
    print()

# Write to assets/bpc_data.js
output_path = os.path.join(PROJECT_DIR, 'assets', 'bpc_data.js')
with open(output_path, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated BPC data with quantity aggregation\n')
    f.write('// Generated by: update_bpc_data_js.py\n')
    f.write('// BPCs are grouped by type_id, ME, TE, and runs\n')
    f.write('const BPC_DATA = ')
    f.write(json.dumps(bpcs, indent=2))
    f.write(';')

print("=" * 70)
print(f"[OK] {output_path} updated successfully with {len(bpcs)} unique BPC groups!")
print("=" * 70)
print()
